/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with staff credentials
         * @description Authenticate a staff user and issue an access token.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current staff user
         * @description Return the authenticated active user.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List campaigns
         * @description Return a status-filtered campaign page.
         */
        get: operations["list_campaigns_api_v1_campaigns_get"];
        put?: never;
        /**
         * Create a campaign
         * @description Create one draft campaign.
         */
        post: operations["create_campaign_api_v1_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get campaign details
         * @description Return one campaign with enrollment-status counts.
         */
        get: operations["get_campaign_api_v1_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a draft campaign
         * @description Update selected fields on a draft campaign.
         */
        patch: operations["update_campaign_api_v1_campaigns__campaign_id__patch"];
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/actions/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Launch a campaign
         * @description Validate a draft and create its donor enrollments.
         */
        post: operations["launch_campaign_api_v1_campaigns__campaign_id__actions_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/actions/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a campaign
         * @description Pause a running campaign.
         */
        post: operations["pause_campaign_api_v1_campaigns__campaign_id__actions_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/actions/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a campaign
         * @description Resume a paused campaign.
         */
        post: operations["resume_campaign_api_v1_campaigns__campaign_id__actions_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List campaign enrollments
         * @description Return filtered enrollments with masked list phone values.
         */
        get: operations["list_campaign_enrollments_api_v1_campaigns__campaign_id__enrollments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List content series
         * @description Return filtered content-series summaries.
         */
        get: operations["list_content_series_api_v1_content_series_get"];
        put?: never;
        /**
         * Create a content series
         * @description Create one draft content series.
         */
        post: operations["create_content_series_api_v1_content_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get content-series details
         * @description Return one series with ordered steps and contents.
         */
        get: operations["get_content_series_api_v1_content_series__series_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a content series
         * @description Update editable series settings.
         */
        patch: operations["update_content_series_api_v1_content_series__series_id__patch"];
        trace?: never;
    };
    "/api/v1/content-series/{series_id}/actions/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate a content series
         * @description Validate every step and activate the series.
         */
        post: operations["activate_content_series_api_v1_content_series__series_id__actions_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series/{series_id}/actions/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive a content series
         * @description Archive a series not used by an active campaign.
         */
        post: operations["archive_content_series_api_v1_content_series__series_id__actions_archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series/{series_id}/actions/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate a content series
         * @description Deep-copy a series into a new draft.
         */
        post: operations["duplicate_content_series_api_v1_content_series__series_id__actions_duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series/{series_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview a rendered series step
         * @description Render one localized simulator message without persisting it.
         */
        post: operations["preview_series_step_api_v1_content_series__series_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series/{series_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a content-series step
         * @description Append a validated step to a series.
         */
        post: operations["create_series_step_api_v1_content_series__series_id__steps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series/{series_id}/steps/actions/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder content-series steps
         * @description Replace the complete step order.
         */
        post: operations["reorder_series_steps_api_v1_content_series__series_id__steps_actions_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content-series/{series_id}/steps/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a content-series step
         * @description Delete a step and return the renumbered series.
         */
        delete: operations["delete_series_step_api_v1_content_series__series_id__steps__step_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a content-series step
         * @description Update one step without changing its order.
         */
        patch: operations["update_series_step_api_v1_content_series__series_id__steps__step_id__patch"];
        trace?: never;
    };
    "/api/v1/donor-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List donor batches
         * @description Return searchable and sortable donor batch summaries.
         */
        get: operations["list_batches_api_v1_donor_batches_get"];
        put?: never;
        /**
         * Import a validated donor batch
         * @description Persist only valid donors from a live preview token.
         */
        post: operations["import_batch_api_v1_donor_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-batches/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview and validate a donor batch upload
         * @description Validate an upload without persisting a donor batch.
         */
        post: operations["preview_batch_api_v1_donor_batches_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-batches/sample-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a donor batch sample CSV
         * @description Return a generated CSV with valid columns and example rows.
         */
        get: operations["download_sample_file_api_v1_donor_batches_sample_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get donor batch details
         * @description Return one donor batch with breakdowns.
         */
        get: operations["get_batch_api_v1_donor_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-batches/{batch_id}/donors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List donors in a batch
         * @description Return filtered donors with masked phone numbers.
         */
        get: operations["list_batch_donors_api_v1_donor_batches__batch_id__donors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/donor-batches/{batch_id}/validation-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a donor batch validation report
         * @description Return persisted invalid-row details for a donor batch.
         */
        get: operations["get_validation_report_api_v1_donor_batches__batch_id__validation_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get enrollment details
         * @description Return a full donor enrollment timeline and follow-up.
         */
        get: operations["get_enrollment_api_v1_enrollments__enrollment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload content-series media
         * @description Validate media bytes and store the asset under a random filename.
         */
        post: operations["upload_media_api_v1_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active staff users
         * @description Return active users, optionally filtered by role.
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API process liveness
         * @description Return success whenever the API process can answer requests.
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check database and Redis readiness
         * @description Report whether both required data services are reachable.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppointmentSlotSummary
         * @description Booked appointment associated with an enrollment.
         */
        AppointmentSlotSummary: {
            /** Center Name */
            center_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /**
         * BatchImportRequest
         * @description Request to persist the valid rows from one preview.
         */
        BatchImportRequest: {
            /** Name */
            name: string;
            /** Preview Token */
            preview_token: string;
        };
        /**
         * BatchPreview
         * @description Upload validation result returned to the review screen.
         */
        BatchPreview: {
            /** Errors */
            errors: components["schemas"]["ValidationIssue"][];
            /** Invalid Rows */
            invalid_rows: number;
            /** Language Breakdown */
            language_breakdown: components["schemas"]["LanguageBreakdown"][];
            /** Original Filename */
            original_filename: string;
            /** Preview Token */
            preview_token: string;
            /** Sample Valid Rows */
            sample_valid_rows: components["schemas"]["DonorPreviewRow"][];
            /** Segment Breakdown */
            segment_breakdown: components["schemas"]["SegmentBreakdown"][];
            /** Total Rows */
            total_rows: number;
            /** Valid Rows */
            valid_rows: number;
            /** Warnings */
            warnings: components["schemas"]["ExistingPhoneWarning"][];
        };
        /** Body_preview_batch_api_v1_donor_batches_preview_post */
        Body_preview_batch_api_v1_donor_batches_preview_post: {
            /**
             * File
             * @description CSV or XLSX donor file
             */
            file: string;
        };
        /** Body_upload_media_api_v1_media_post */
        Body_upload_media_api_v1_media_post: {
            /**
             * File
             * @description JPG, PNG, WebP, or MP4 media
             */
            file: string;
        };
        /**
         * CampaignCreate
         * @description Create one draft campaign.
         */
        CampaignCreate: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Name */
            name: string;
            /**
             * Primary Series Id
             * Format: uuid
             */
            primary_series_id: string;
            /**
             * Secondary Series Id
             * Format: uuid
             */
            secondary_series_id: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
        };
        /**
         * CampaignDetail
         * @description Campaign summary with every enrollment-status count.
         */
        CampaignDetail: {
            batch: components["schemas"]["NamedResourceSummary"];
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UploadedBySummary"];
            /** Enrollment Count */
            enrollment_count: number;
            /** Enrollment Counts */
            enrollment_counts: {
                [key: string]: number;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Launched At */
            launched_at: string | null;
            /** Name */
            name: string;
            primary_series: components["schemas"]["NamedResourceSummary"];
            /** Responded Count */
            responded_count: number;
            /** Response Rate */
            response_rate: number;
            secondary_series: components["schemas"]["NamedResourceSummary"];
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            status: components["schemas"]["CampaignStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CampaignOut
         * @description Campaign list representation.
         */
        CampaignOut: {
            batch: components["schemas"]["NamedResourceSummary"];
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UploadedBySummary"];
            /** Enrollment Count */
            enrollment_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Launched At */
            launched_at: string | null;
            /** Name */
            name: string;
            primary_series: components["schemas"]["NamedResourceSummary"];
            /** Responded Count */
            responded_count: number;
            /** Response Rate */
            response_rate: number;
            secondary_series: components["schemas"]["NamedResourceSummary"];
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            status: components["schemas"]["CampaignStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CampaignPage
         * @description Paginated campaign summaries.
         */
        CampaignPage: {
            /** Items */
            items: components["schemas"]["CampaignOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * CampaignStatus
         * @enum {string}
         */
        CampaignStatus: "draft" | "scheduled" | "running" | "paused" | "completed";
        /**
         * CampaignUpdate
         * @description Update selected draft campaign settings.
         */
        CampaignUpdate: {
            /** Batch Id */
            batch_id?: string | null;
            /** Name */
            name?: string | null;
            /** Primary Series Id */
            primary_series_id?: string | null;
            /** Secondary Series Id */
            secondary_series_id?: string | null;
            /** Start At */
            start_at?: string | null;
        };
        /**
         * ContentSeriesCreate
         * @description Create one draft content series.
         */
        ContentSeriesCreate: {
            /** Description */
            description?: string | null;
            kind: components["schemas"]["SeriesKind"];
            /** Languages */
            languages: components["schemas"]["LanguageCode"][];
            /** Name */
            name: string;
            /**
             * Response Window Hours
             * @default 48
             */
            response_window_hours: number;
            /** Tag Names */
            tag_names?: string[];
        };
        /**
         * ContentSeriesDetail
         * @description Content series with its ordered steps.
         */
        ContentSeriesDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UploadedBySummary"];
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["SeriesKind"];
            /** Languages */
            languages: components["schemas"]["LanguageCode"][];
            /** Name */
            name: string;
            /** Response Window Hours */
            response_window_hours: number;
            status: components["schemas"]["SeriesStatus"];
            /** Step Count */
            step_count: number;
            /** Steps */
            steps: components["schemas"]["SeriesStepOut"][];
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ContentSeriesOut
         * @description Content-series list representation.
         */
        ContentSeriesOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by: components["schemas"]["UploadedBySummary"];
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["SeriesKind"];
            /** Languages */
            languages: components["schemas"]["LanguageCode"][];
            /** Name */
            name: string;
            /** Response Window Hours */
            response_window_hours: number;
            status: components["schemas"]["SeriesStatus"];
            /** Step Count */
            step_count: number;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ContentSeriesPage
         * @description Paginated content-series summaries.
         */
        ContentSeriesPage: {
            /** Items */
            items: components["schemas"]["ContentSeriesOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ContentSeriesUpdate
         * @description Update selected content-series settings.
         */
        ContentSeriesUpdate: {
            /** Description */
            description?: string | null;
            kind?: components["schemas"]["SeriesKind"] | null;
            /** Languages */
            languages?: components["schemas"]["LanguageCode"][] | null;
            /** Name */
            name?: string | null;
            /** Response Window Hours */
            response_window_hours?: number | null;
            /** Tag Names */
            tag_names?: string[] | null;
        };
        /**
         * DeclineReason
         * @enum {string}
         */
        DeclineReason: "travelling" | "health" | "recently_donated" | "not_interested" | "other";
        /**
         * DonorBatchDetail
         * @description Batch summary with segment and language counts.
         */
        DonorBatchDetail: {
            /** Campaign Count */
            campaign_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Invalid Rows */
            invalid_rows: number;
            /** Language Breakdown */
            language_breakdown: components["schemas"]["LanguageBreakdown"][];
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** Segment Breakdown */
            segment_breakdown: components["schemas"]["SegmentBreakdown"][];
            /** Total Rows */
            total_rows: number;
            uploaded_by: components["schemas"]["UploadedBySummary"];
            /** Valid Rows */
            valid_rows: number;
        };
        /**
         * DonorBatchOut
         * @description Summary of one imported donor batch.
         */
        DonorBatchOut: {
            /** Campaign Count */
            campaign_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Invalid Rows */
            invalid_rows: number;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** Total Rows */
            total_rows: number;
            uploaded_by: components["schemas"]["UploadedBySummary"];
            /** Valid Rows */
            valid_rows: number;
        };
        /**
         * DonorBatchPage
         * @description Paginated donor batch summaries.
         */
        DonorBatchPage: {
            /** Items */
            items: components["schemas"]["DonorBatchOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * DonorOut
         * @description Masked donor row for staff batch browsing.
         */
        DonorOut: {
            /** Blood Group */
            blood_group: string | null;
            /** City */
            city: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            language: components["schemas"]["LanguageCode"];
            /** Last Donation Date */
            last_donation_date: string | null;
            /** Phone E164 */
            phone_e164: string;
            /** Segment */
            segment: string;
        };
        /**
         * DonorPage
         * @description Paginated donors within one batch.
         */
        DonorPage: {
            /** Items */
            items: components["schemas"]["DonorOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * DonorPreviewRow
         * @description One normalized valid donor shown during review.
         */
        DonorPreviewRow: {
            /** Blood Group */
            blood_group?: string | null;
            /** City */
            city?: string | null;
            language: components["schemas"]["LanguageCode"];
            /** Last Donation Date */
            last_donation_date?: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Row */
            row: number;
            /** Segment */
            segment: string;
        };
        /**
         * EnrollmentDetail
         * @description Enrollment with full donor data and related activity.
         */
        EnrollmentDetail: {
            appointment: components["schemas"]["AppointmentSlotSummary"] | null;
            campaign: components["schemas"]["NamedResourceSummary"];
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            current_series_kind: components["schemas"]["SeriesKind"] | null;
            /** Current Step Order */
            current_step_order: number | null;
            decline_reason: components["schemas"]["DeclineReason"] | null;
            donor: components["schemas"]["EnrollmentDonorOut"];
            follow_up: components["schemas"]["FollowUpSummary"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Next Action At */
            next_action_at: string | null;
            /** Responded At */
            responded_at: string | null;
            status: components["schemas"]["EnrollmentStatus"];
            /** Timeline */
            timeline: components["schemas"]["EnrollmentTimelineItem"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EnrollmentDonorOut
         * @description Donor information returned with an enrollment.
         */
        EnrollmentDonorOut: {
            /** Blood Group */
            blood_group: string | null;
            /** City */
            city: string | null;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            language: components["schemas"]["LanguageCode"];
            /** Last Donation Date */
            last_donation_date: string | null;
            /** Phone E164 */
            phone_e164: string;
            /** Segment */
            segment: string;
        };
        /**
         * EnrollmentOut
         * @description Enrollment list representation.
         */
        EnrollmentOut: {
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            current_series_kind: components["schemas"]["SeriesKind"] | null;
            /** Current Step Order */
            current_step_order: number | null;
            decline_reason: components["schemas"]["DeclineReason"] | null;
            donor: components["schemas"]["EnrollmentDonorOut"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Next Action At */
            next_action_at: string | null;
            /** Responded At */
            responded_at: string | null;
            status: components["schemas"]["EnrollmentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EnrollmentPage
         * @description Paginated campaign enrollments.
         */
        EnrollmentPage: {
            /** Items */
            items: components["schemas"]["EnrollmentOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * EnrollmentStatus
         * @enum {string}
         */
        EnrollmentStatus: "pending" | "in_primary" | "in_secondary" | "escalated" | "confirmed" | "reschedule_requested" | "rescheduled" | "declined" | "invalid_number" | "undeliverable";
        /**
         * EnrollmentTimelineItem
         * @description Chronological message or response event.
         */
        EnrollmentTimelineItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            message?: components["schemas"]["MessageTimelineEntry"] | null;
            response?: components["schemas"]["ResponseTimelineEntry"] | null;
            /**
             * Type
             * @enum {string}
             */
            type: "message" | "response";
        };
        /**
         * ExistingPhoneWarning
         * @description A valid phone that also appears in an earlier batch.
         */
        ExistingPhoneWarning: {
            /** Existing Batch Name */
            existing_batch_name: string;
            /** Phone */
            phone: string;
            /** Row */
            row: number;
        };
        /**
         * FollowUpPriority
         * @enum {string}
         */
        FollowUpPriority: "normal" | "high";
        /**
         * FollowUpStatus
         * @enum {string}
         */
        FollowUpStatus: "open" | "in_progress" | "done";
        /**
         * FollowUpSummary
         * @description Current or most recent coordinator follow-up.
         */
        FollowUpSummary: {
            /** Assigned To Id */
            assigned_to_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            priority: components["schemas"]["FollowUpPriority"];
            status: components["schemas"]["FollowUpStatus"];
            type: components["schemas"]["FollowUpType"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FollowUpType
         * @enum {string}
         */
        FollowUpType: "confirmed" | "reschedule" | "declined" | "needs_call";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LanguageBreakdown
         * @description Preview or batch count for one donor language.
         */
        LanguageBreakdown: {
            /** Count */
            count: number;
            language: components["schemas"]["LanguageCode"];
        };
        /**
         * LanguageCode
         * @enum {string}
         */
        LanguageCode: "en" | "ur";
        /**
         * LiveResponse
         * @description Liveness probe payload.
         */
        LiveResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * LoginRequest
         * @description Credentials submitted to the login endpoint.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "none" | "image" | "video";
        /**
         * MediaUploadOut
         * @description Public URL and detected kind of one uploaded media file.
         */
        MediaUploadOut: {
            media_type: components["schemas"]["MediaType"];
            /** Url */
            url: string;
        };
        /**
         * MessageCategory
         * @enum {string}
         */
        MessageCategory: "utility" | "marketing";
        /**
         * MessageDirection
         * @enum {string}
         */
        MessageDirection: "outbound" | "inbound";
        /**
         * MessageKind
         * @enum {string}
         */
        MessageKind: "template" | "text" | "interactive" | "button_reply";
        /**
         * MessageStatus
         * @enum {string}
         */
        MessageStatus: "queued" | "sent" | "delivered" | "read" | "failed";
        /**
         * MessageTimelineEntry
         * @description Message data embedded in an enrollment timeline.
         */
        MessageTimelineEntry: {
            /** Body */
            body: string;
            /** Delivered At */
            delivered_at: string | null;
            direction: components["schemas"]["MessageDirection"];
            kind: components["schemas"]["MessageKind"];
            media_type: components["schemas"]["MediaType"];
            /** Media Url */
            media_url: string | null;
            /** Read At */
            read_at: string | null;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["MessageStatus"];
        };
        /**
         * NamedResourceSummary
         * @description Identifier and display name for a related resource.
         */
        NamedResourceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * PreviewButtonOut
         * @description Quick reply localized for simulator preview.
         */
        PreviewButtonOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /**
         * QuickReplyButtonInput
         * @description Localized quick-reply definition.
         */
        QuickReplyButtonInput: {
            /** Id */
            id: string;
            /**
             * Intent
             * @enum {string}
             */
            intent: "confirm" | "reschedule" | "decline";
            /** Labels */
            labels: {
                [key: string]: string;
            };
        };
        /**
         * QuickReplyButtonOut
         * @description Stored multilingual quick-reply definition.
         */
        QuickReplyButtonOut: {
            /** Id */
            id: string;
            /**
             * Intent
             * @enum {string}
             */
            intent: "confirm" | "reschedule" | "decline";
            /** Labels */
            labels: {
                [key: string]: string;
            };
        };
        /**
         * ReadyResponse
         * @description Successful readiness probe payload.
         */
        ReadyResponse: {
            /** Checks */
            checks: {
                [key: string]: "ok";
            };
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /**
         * ResponseIntent
         * @enum {string}
         */
        ResponseIntent: "confirm" | "reschedule" | "decline" | "question" | "unknown";
        /**
         * ResponseSource
         * @enum {string}
         */
        ResponseSource: "button" | "agent";
        /**
         * ResponseTimelineEntry
         * @description Classified response data embedded in an enrollment timeline.
         */
        ResponseTimelineEntry: {
            /** Confidence */
            confidence: string;
            decline_reason: components["schemas"]["DeclineReason"] | null;
            /** Detected Language */
            detected_language: string;
            intent: components["schemas"]["ResponseIntent"];
            /** Requested Date */
            requested_date: string | null;
            source: components["schemas"]["ResponseSource"];
        };
        /**
         * SegmentBreakdown
         * @description Preview or batch count for one segment.
         */
        SegmentBreakdown: {
            /** Count */
            count: number;
            /** Segment */
            segment: string;
        };
        /**
         * SeriesKind
         * @enum {string}
         */
        SeriesKind: "primary" | "secondary";
        /**
         * SeriesPreviewInput
         * @description Select a step, language, and optional real donor.
         */
        SeriesPreviewInput: {
            /** Donor Id */
            donor_id?: string | null;
            language: components["schemas"]["LanguageCode"];
            /**
             * Step Id
             * Format: uuid
             */
            step_id: string;
        };
        /**
         * SeriesPreviewMessage
         * @description Non-persistent outbound message rendered for the simulator preview.
         */
        SeriesPreviewMessage: {
            /** Body */
            body: string;
            /** Button Id */
            button_id?: null;
            /** Buttons */
            buttons: components["schemas"]["PreviewButtonOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Delivered At */
            delivered_at?: null;
            direction: components["schemas"]["MessageDirection"];
            /** Donor Id */
            donor_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["MessageKind"];
            media_type: components["schemas"]["MediaType"];
            /** Media Url */
            media_url: string | null;
            /** Read At */
            read_at?: null;
            /** Reply To Message Id */
            reply_to_message_id?: null;
            /** Sent At */
            sent_at?: null;
            status: components["schemas"]["MessageStatus"];
        };
        /**
         * SeriesReorderInput
         * @description Complete desired ordering for one series.
         */
        SeriesReorderInput: {
            /** Step Ids */
            step_ids: string[];
        };
        /**
         * SeriesStatus
         * @enum {string}
         */
        SeriesStatus: "draft" | "active" | "archived";
        /**
         * SeriesStepContentInput
         * @description Localized body supplied for a series step.
         */
        SeriesStepContentInput: {
            /** Body */
            body: string;
            language: components["schemas"]["LanguageCode"];
        };
        /**
         * SeriesStepContentOut
         * @description Stored localized step body.
         */
        SeriesStepContentOut: {
            /** Body */
            body: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            language: components["schemas"]["LanguageCode"];
        };
        /**
         * SeriesStepInput
         * @description Create one ordered content-series step.
         */
        SeriesStepInput: {
            /** Buttons */
            buttons?: components["schemas"]["QuickReplyButtonInput"][];
            category: components["schemas"]["MessageCategory"];
            /** Contents */
            contents?: components["schemas"]["SeriesStepContentInput"][];
            /** Delay Days */
            delay_days: number;
            /** @default none */
            media_type: components["schemas"]["MediaType"];
            /** Media Url */
            media_url?: string | null;
        };
        /**
         * SeriesStepOut
         * @description One ordered series step with localized contents.
         */
        SeriesStepOut: {
            /** Buttons */
            buttons: components["schemas"]["QuickReplyButtonOut"][];
            category: components["schemas"]["MessageCategory"];
            /** Contents */
            contents: components["schemas"]["SeriesStepContentOut"][];
            /** Delay Days */
            delay_days: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            media_type: components["schemas"]["MediaType"];
            /** Media Url */
            media_url: string | null;
            /** Step Order */
            step_order: number;
        };
        /**
         * SeriesStepUpdate
         * @description Replace selected fields on one series step.
         */
        SeriesStepUpdate: {
            /** Buttons */
            buttons?: components["schemas"]["QuickReplyButtonInput"][] | null;
            category?: components["schemas"]["MessageCategory"] | null;
            /** Contents */
            contents?: components["schemas"]["SeriesStepContentInput"][] | null;
            /** Delay Days */
            delay_days?: number | null;
            media_type?: components["schemas"]["MediaType"] | null;
            /** Media Url */
            media_url?: string | null;
        };
        /**
         * TokenResponse
         * @description Access token and authenticated user returned after login.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["UserOut"];
        };
        /**
         * UploadedBySummary
         * @description Minimal uploader identity displayed with a batch.
         */
        UploadedBySummary: {
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * UserOut
         * @description Public staff-user fields.
         */
        UserOut: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserPage
         * @description Paginated active-user response.
         */
        UserPage: {
            /** Items */
            items: components["schemas"]["UserOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "coordinator";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationIssue
         * @description One row-level upload validation error.
         */
        ValidationIssue: {
            /** Field */
            field: string;
            /** Reason */
            reason: string;
            /** Row */
            row: number;
            /** Value */
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["CampaignStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_campaign_api_v1_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_v1_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_campaign_api_v1_campaigns__campaign_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_campaign_api_v1_campaigns__campaign_id__actions_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_campaign_api_v1_campaigns__campaign_id__actions_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_campaign_api_v1_campaigns__campaign_id__actions_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaign_enrollments_api_v1_campaigns__campaign_id__enrollments_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["EnrollmentStatus"] | null;
                search?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_content_series_api_v1_content_series_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["SeriesKind"] | null;
                status?: components["schemas"]["SeriesStatus"] | null;
                tag?: string | null;
                language?: components["schemas"]["LanguageCode"] | null;
                search?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_content_series_api_v1_content_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentSeriesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_series_api_v1_content_series__series_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_content_series_api_v1_content_series__series_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentSeriesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_content_series_api_v1_content_series__series_id__actions_activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_content_series_api_v1_content_series__series_id__actions_archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_content_series_api_v1_content_series__series_id__actions_duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_series_step_api_v1_content_series__series_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesPreviewInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesPreviewMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_series_step_api_v1_content_series__series_id__steps_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesStepInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesStepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_series_steps_api_v1_content_series__series_id__steps_actions_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesReorderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_series_step_api_v1_content_series__series_id__steps__step_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_series_step_api_v1_content_series__series_id__steps__step_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesStepUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesStepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_donor_batches_get: {
        parameters: {
            query?: {
                search?: string | null;
                sort?: "created_at" | "-created_at" | "name" | "-name";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonorBatchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_batch_api_v1_donor_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonorBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_batch_api_v1_donor_batches_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_batch_api_v1_donor_batches_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_sample_file_api_v1_donor_batches_sample_file_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_batch_api_v1_donor_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonorBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batch_donors_api_v1_donor_batches__batch_id__donors_get: {
        parameters: {
            query?: {
                segment?: string | null;
                language?: components["schemas"]["LanguageCode"] | null;
                search?: string | null;
                sort?: "created_at" | "-created_at" | "full_name" | "-full_name";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DonorPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_validation_report_api_v1_donor_batches__batch_id__validation_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationIssue"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enrollment_api_v1_enrollments__enrollment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_media_api_v1_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_media_api_v1_media_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                role?: components["schemas"]["UserRole"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description A required dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
